In [36]:
import os
import re

import numpy as np
import pandas as pd

from tqdm import tqdm

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

from xgboost import XGBClassifier

from collections import Counter

import joblib

In [37]:
LOG_FILE = r"../../Dataset/HDFS/HDFS_1/HDFS.log"

LABEL_FILE = r"../../Dataset/HDFS/HDFS_1/anomaly_label.csv"

In [38]:
print(os.path.exists(LOG_FILE))

print(os.path.exists(LABEL_FILE))

True
True

In [39]:
labels_df = pd.read_csv(LABEL_FILE)

labels_df.head()

                    BlockId    Label
0  blk_-1608999687919862906   Normal
1   blk_7503483334202473044   Normal
2  blk_-3544583377289625738  Anomaly
3  blk_-9073992586687739851   Normal
4   blk_7854771516489510256   Normal

In [40]:
print(labels_df.columns)

Index(['BlockId', 'Label'], dtype='str')

In [41]:
with open(
    LOG_FILE,
    "r",
    encoding="utf-8",
    errors="ignore"
) as f:

    logs = f.readlines()

print("Total Logs:", len(logs))

Total Logs: 11175629

In [42]:
block_pattern = r'(blk_-?\d+)'

In [43]:
block_logs = {}

for line in tqdm(logs):

    match = re.search(block_pattern, line)

    if match:

        block_id = match.group(1)

        if block_id not in block_logs:

            block_logs[block_id] = []

        block_logs[block_id].append(line.strip())

100%|██████████| 11175629/11175629 [00:29<00:00, 380404.53it/s]

In [44]:
print("Total Blocks:", len(block_logs))

Total Blocks: 575061

In [45]:
data = []

for block_id, log_lines in block_logs.items():

    combined_logs = " ".join(log_lines)

    data.append({

        "BlockId": block_id,

        "Logs": combined_logs
    })

df = pd.DataFrame(data)

df.head()

                    BlockId                                               Logs
0  blk_-1608999687919862906  081109 203518 143 INFO dfs.DataNode$DataXceive...
1   blk_7503483334202473044  081109 203520 142 INFO dfs.DataNode$DataXceive...
2  blk_-3544583377289625738  081109 203521 145 INFO dfs.DataNode$DataXceive...
3  blk_-9073992586687739851  081109 203523 143 INFO dfs.DataNode$DataXceive...
4   blk_7854771516489510256  081109 203529 148 INFO dfs.DataNode$DataXceive...

In [46]:
# =========================================
# MERGE LOGS WITH LABELS
# =========================================

df = df.merge(

    labels_df,

    on="BlockId",

    how="inner"
)

print(df.shape)

df.head()

(575061, 3)

,BlockId,Logs,Label
0,blk_-1608999687919862906,081109 203518 143 INFO dfs.DataNode$DataXceive...,Normal
1,blk_7503483334202473044,081109 203520 142 INFO dfs.DataNode$DataXceive...,Normal
2,blk_-3544583377289625738,081109 203521 145 INFO dfs.DataNode$DataXceive...,Anomaly
3,blk_-9073992586687739851,081109 203523 143 INFO dfs.DataNode$DataXceive...,Normal
4,blk_7854771516489510256,081109 203529 148 INFO dfs.DataNode$DataXceive...,Normal

In [47]:
print("\nLabel Distribution:\n")

print(df["Label"].value_counts())

Label Distribution:

Label
Normal     558223
Anomaly     16838
Name: count, dtype: int64

In [48]:
label_encoder = LabelEncoder()

y = label_encoder.fit_transform(
    df["Label"]
)

In [49]:
for i, label in enumerate(label_encoder.classes_):

    print(i, "->", label)

0 -> Anomaly
1 -> Normal

In [50]:
# =========================================
# SPLIT RAW TEXT FIRST
# =========================================

X_text = df["Logs"]

X_train_text, X_test_text, y_train, y_test = train_test_split(

    X_text,
    y,

    test_size=0.2,

    random_state=42,

    stratify=y
)

print("\nTraining Samples:", len(X_train_text))

print("Testing Samples:", len(X_test_text))

Training Samples: 460048
Testing Samples: 115013

In [51]:
# =========================================
# TF-IDF FEATURE ENGINEERING
# =========================================

vectorizer = TfidfVectorizer(

    max_features=5000,

    stop_words='english'
)

# FIT ONLY ON TRAIN DATA

X_train = vectorizer.fit_transform(
    X_train_text
)

# TRANSFORM TEST DATA

X_test = vectorizer.transform(
    X_test_text
)

print("\nTrain Shape:", X_train.shape)

print("Test Shape:", X_test.shape)

Train Shape: (460048, 5000)
Test Shape: (115013, 5000)

In [52]:
print("\nTraining Distribution:\n")

print(Counter(y_train))

Training Distribution:

Counter({np.int64(1): 446578, np.int64(0): 13470})

In [53]:
print("\nAnomaly Ratio:")

print(df["Label"].value_counts(normalize=True))

Anomaly Ratio:
Label
Normal     0.97072
Anomaly    0.02928
Name: proportion, dtype: float64

In [54]:
model = XGBClassifier(

    n_estimators=150,

    max_depth=5,

    learning_rate=0.05,

    subsample=0.8,

    colsample_bytree=0.8,

    objective='binary:logistic',

    eval_metric='logloss',

    n_jobs=-1,

    random_state=42
)

In [55]:
model.fit(

    X_train,
    y_train,

    eval_set=[(X_test, y_test)],

    verbose=True
)

[0]	validation_0-logloss:0.08591
[1]	validation_0-logloss:0.07580
[2]	validation_0-logloss:0.06837
[3]	validation_0-logloss:0.06245
[4]	validation_0-logloss:0.05749
[5]	validation_0-logloss:0.05337
[6]	validation_0-logloss:0.04962
[7]	validation_0-logloss:0.04626
[8]	validation_0-logloss:0.04325
[9]	validation_0-logloss:0.04060
[10]	validation_0-logloss:0.03811
[11]	validation_0-logloss:0.03584
[12]	validation_0-logloss:0.03374
[13]	validation_0-logloss:0.03189
[14]	validation_0-logloss:0.03009
[15]	validation_0-logloss:0.02841
[16]	validation_0-logloss:0.02686
[17]	validation_0-logloss:0.02540
[18]	validation_0-logloss:0.02404
[19]	validation_0-logloss:0.02283
[20]	validation_0-logloss:0.02168
[21]	validation_0-logloss:0.02055
[22]	validation_0-logloss:0.01949
[23]	validation_0-logloss:0.01860
[24]	validation_0-logloss:0.01767
[25]	validation_0-logloss:0.01679
[26]	validation_0-logloss:0.01595
[27]	validation_0-logloss:0.01522
[28]	validation_0-logloss:0.01450
[29]	validation_0-logloss:0.01385
[30]	validation_0-logloss:0.01318
[31]	validation_0-logloss:0.01255
[32]	validation_0-logloss:0.01195
[33]	validation_0-logloss:0.01139
[34]	validation_0-logloss:0.01085
[35]	validation_0-logloss:0.01034
[36]	validation_0-logloss:0.00990
[37]	validation_0-logloss:0.00947
[38]	validation_0-logloss:0.00904
[39]	validation_0-logloss:0.00863
[40]	validation_0-logloss:0.00825
[41]	validation_0-logloss:0.00788
[42]	validation_0-logloss:0.00753
[43]	validation_0-logloss:0.00719
[44]	validation_0-logloss:0.00688
[45]	validation_0-logloss:0.00658
[46]	validation_0-logloss:0.00629
[47]	validation_0-logloss:0.00602
[48]	validation_0-logloss:0.00576
[49]	validation_0-logloss:0.00552
[50]	validation_0-logloss:0.00528
[51]	validation_0-logloss:0.00506
[52]	validation_0-logloss:0.00486
[53]	validation_0-logloss:0.00466
[54]	validation_0-logloss:0.00447
[55]	validation_0-logloss:0.00429
[56]	validation_0-logloss:0.00412
[57]	validation_0-logloss:0.00397
[58]	validation_0-logloss:0.00381
[59]	validation_0-logloss:0.00367
[60]	validation_0-logloss:0.00353
[61]	validation_0-logloss:0.00340
[62]	validation_0-logloss:0.00327
[63]	validation_0-logloss:0.00315
[64]	validation_0-logloss:0.00304
[65]	validation_0-logloss:0.00293
[66]	validation_0-logloss:0.00284
[67]	validation_0-logloss:0.00274
[68]	validation_0-logloss:0.00265
[69]	validation_0-logloss:0.00256
[70]	validation_0-logloss:0.00248
[71]	validation_0-logloss:0.00239
[72]	validation_0-logloss:0.00231
[73]	validation_0-logloss:0.00224
[74]	validation_0-logloss:0.00217
[75]	validation_0-logloss:0.00210
[76]	validation_0-logloss:0.00204
[77]	validation_0-logloss:0.00198
[78]	validation_0-logloss:0.00192
[79]	validation_0-logloss:0.00186
[80]	validation_0-logloss:0.00180
[81]	validation_0-logloss:0.00175
[82]	validation_0-logloss:0.00170
[83]	validation_0-logloss:0.00165
[84]	validation_0-logloss:0.00160
[85]	validation_0-logloss:0.00156
[86]	validation_0-logloss:0.00152
[87]	validation_0-logloss:0.00148
[88]	validation_0-logloss:0.00144
[89]	validation_0-logloss:0.00141
[90]	validation_0-logloss:0.00138
[91]	validation_0-logloss:0.00135
[92]	validation_0-logloss:0.00131
[93]	validation_0-logloss:0.00128
[94]	validation_0-logloss:0.00125
[95]	validation_0-logloss:0.00123
[96]	validation_0-logloss:0.00120
[97]	validation_0-logloss:0.00117
[98]	validation_0-logloss:0.00115
[99]	validation_0-logloss:0.00112
[100]	validation_0-logloss:0.00110
[101]	validation_0-logloss:0.00108
[102]	validation_0-logloss:0.00107
[103]	validation_0-logloss:0.00105
[104]	validation_0-logloss:0.00103
[105]	validation_0-logloss:0.00101
[106]	validation_0-logloss:0.00100
[107]	validation_0-logloss:0.00098
[108]	validation_0-logloss:0.00096
[109]	validation_0-logloss:0.00095
[110]	validation_0-logloss:0.00094
[111]	validation_0-logloss:0.00092
[112]	validation_0-logloss:0.00091
[113]	validation_0-logloss:0.00090
[114]	validation_0-logloss:0.00089
[115]	validation_0-logloss:0.00088
[116]	validation_0-logloss:0.00087
[117]	validation_0-logloss:0.00085
[118]	validation_0-logloss:0.00084
[119]	validation_0-logloss:0.00084
[120]	validation_0-logloss:0.00083
[121]	validation_0-logloss:0.00082
[122]	validation_0-logloss:0.00081
[123]	validation_0-logloss:0.00081
[124]	validation_0-logloss:0.00080
[125]	validation_0-logloss:0.00079
[126]	validation_0-logloss:0.00079
[127]	validation_0-logloss:0.00078
[128]	validation_0-logloss:0.00078
[129]	validation_0-logloss:0.00077
[130]	validation_0-logloss:0.00077
[131]	validation_0-logloss:0.00076
[132]	validation_0-logloss:0.00076
[133]	validation_0-logloss:0.00075
[134]	validation_0-logloss:0.00074
[135]	validation_0-logloss:0.00074
[136]	validation_0-logloss:0.00073
[137]	validation_0-logloss:0.00073
[138]	validation_0-logloss:0.00073
[139]	validation_0-logloss:0.00072
[140]	validation_0-logloss:0.00072
[141]	validation_0-logloss:0.00071
[142]	validation_0-logloss:0.00071
[143]	validation_0-logloss:0.00071
[144]	validation_0-logloss:0.00070
[145]	validation_0-logloss:0.00070
[146]	validation_0-logloss:0.00070
[147]	validation_0-logloss:0.00070
[148]	validation_0-logloss:0.00069
[149]	validation_0-logloss:0.00069

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=150, n_jobs=-1,
              num_parallel_tree=None, ...)

In [56]:
y_prob = model.predict_proba(X_test)

y_pred = np.argmax(y_prob, axis=1)

In [57]:
train_pred = model.predict(X_train)

train_accuracy = accuracy_score(
    y_train,
    train_pred
)

print(f"\nTraining Accuracy: {train_accuracy:.4f}")

Training Accuracy: 0.9999

In [58]:
accuracy = accuracy_score(y_test, y_pred)

print(f"\nTest Accuracy: {accuracy:.4f}")

Test Accuracy: 0.9998

In [59]:
print(

    classification_report(

        y_test,
        y_pred
    )
)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3368
           1       1.00      1.00      1.00    111645

    accuracy                           1.00    115013
   macro avg       1.00      1.00      1.00    115013
weighted avg       1.00      1.00      1.00    115013

In [60]:
cm = confusion_matrix(
    y_test,
    y_pred
)

print(cm)

[[  3355     13]
 [    10 111635]]

In [61]:
# =========================================
# CHECK OVERFITTING GAP
# =========================================

gap = train_accuracy - accuracy

print(f"\nOverfitting Gap: {gap:.4f}")

Overfitting Gap: 0.0001

In [62]:
os.makedirs(

    "../../trained_models/hdfs",

    exist_ok=True
)

joblib.dump(

    model,

    "../../trained_models/hdfs/hdfs_xgboost_model.pkl"
)

['../../trained_models/hdfs/hdfs_xgboost_model.pkl']

In [63]:
joblib.dump(

    vectorizer,

    "../../trained_models/hdfs/hdfs_vectorizer.pkl"
)

['../../trained_models/hdfs/hdfs_vectorizer.pkl']

In [64]:
joblib.dump(

    label_encoder,

    "../../trained_models/hdfs/hdfs_label_encoder.pkl"
)

['../../trained_models/hdfs/hdfs_label_encoder.pkl']

In [65]:
print("===================================")

print("AEGIS HDFS Anomaly Detection Ready")

print("===================================")

print("Distributed Anomaly Model Saved")

===================================
AEGIS HDFS Anomaly Detection Ready
===================================
Distributed Anomaly Model Saved